
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 6
      registerHealthIndicator: true
      recordExceptions:
        - java.lang.ClassCastException
  instances:
    demo:
      baseConfig: default

#logging:
#  level:
#    io.github.resilience4j: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
